name: todos_repository_local_storage
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  todos_repository_core:
    git:
      url: git@github.com:moyaying/flutter_architecture_samples.git
      path: todos_repository_core
  rxdart: ^0.23.1
  key_value_store:

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  mockito:
